name: check if notification is sent to gchat

on:
  issue_comment:
    types: [created]

permissions: write-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_NAME: ${{ github.repository }}
  EVENT: ${{ github.event.action }} 
  WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK}}

 
jobs:
  Google-Chat-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Google Chat Integration
        uses: ./