name: Google-Chat-Integration

on:
  repository_dispatch:
    types: [trigger-gchat]

permissions: write-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_NAME: ${{ github.repository }}
  WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}

jobs:
  Google-Chat-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Google Chat Integration
        uses: ./
        with:
          EVENT_CHECK_VARIABLE: ${{ github.event.client_payload.EVENT_CHECK_VARIABLE }}
          PR_NUMBER: ${{ github.event.client_payload.PR_NUMBER }}
          VERSION_FILE: ${{ github.event.client_payload.VERSION_FILE}}
