name: Google-Chat-Integration

on:
  workflow_run:
    workflows: ["PR Check"]
    types: [completed]

permissions: write-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_NAME: ${{ github.repository }}
  WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}

jobs:
  Google-Chat-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Download the artifact
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: pr-info
          path: pr_info.txt

      # Read the contents of pr-info.txt
      - name: Read Artifact
        run: |
          pr_info=$(cat pr-info.txt)
          echo "PR Info: $pr_info"
          # Now you can use the PR info in your workflow
        