# Description: This workflow triggers on a pull request and checks for PR Description, Target Checker, Version, and closes the PR if it has a DO NOT MERGE label.
name: PR Check 
on:
  pull_request:
    types: [opened, edited, reopened,labeled]
   
permissions: write-all    
      
env:
  EVENT_CHECK_VARIABLE: 'pull'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_NAME: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  
  
 
jobs:
    Check-PR:
      runs-on: ubuntu-latest
      steps:
        - name: Set PR Info
          id: set_pr_info
          run: |
            echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> pr_info.txt
            echo "EVENT=${{ github.event.action }}" >> pr_info.txt
            echo "EVENT_CHECK_VARIABLE= $EVENT_CHECK_VARIABLE " >> pr_info.txt 
        - name: Checkout
          uses: actions/checkout@v3
        - name: Version Check
          id: latestTag
          run: |
            if [ -f "VERSION" ]; then
              echo "File is present"        
              version_file=$(cat VERSION)
              echo "Version from version_file -> $version_file"
              echo "version_file=$version_file" >> $GITHUB_OUTPUT
            else 
             echo "No file"
            fi
        - name: PR Description, Target Checker, Version and Close the PR having DO NOT MERGE LABEL
          uses: ./
          env:
            VERSION_FILE: ${{ steps.latestTag.outputs.version_file }}
          
        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
            name: pr-info
            path: pr_info.txt        
            
      
      