name: PR Check 
on:
  pull_request:
    types: [opened, edited, reopened, labeled]
   
permissions: write-all   # <- Add a colon here    
      
env:
  EVENT_CHECK_VARIABLE: 'pull'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_NAME: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  
jobs:
  Check-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Set PR Info
        id: set_pr_info
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> pr_info.txt
          echo "EVENT=${{ github.event.action }}" >> pr_info.txt
          echo "EVENT_CHECK_VARIABLE= $EVENT_CHECK_VARIABLE " >> pr_info.txt 
          cat pr_info.txt
      
      # Troubleshooting Step 1: Check the contents of the pr_info.txt file
      - name: Check pr_info.txt content
        run: |
          cat pr_info.txt
          
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Version Check
        id: latestTag
        run: |
          if [ -f "VERSION" ]; then
            echo "File is present"        
            version_file=$(cat VERSION)
            echo "Version from version_file -> $version_file"
            echo "version_file=$version_file" >> $GITHUB_OUTPUT
          else 
            echo "No file"
          fi
      
      # Troubleshooting Step 2: Check if the VERSION file exists and its content
      - name: Check VERSION file
        run: |
          ls -l VERSION
          cat VERSION || echo "VERSION file does not exist"
      
      - name: PR Description, Target Checker, Version and Close the PR having DO NOT MERGE LABEL
        uses: ./ # Assuming this is your custom action
        env:
          VERSION_FILE: ${{ steps.latestTag.outputs.version_file }}
      
      - name: Upload Artifact
        id: upload_artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr-info
          path: pr_info.txt
          
      # Add this step to debug the uploaded artifact size
      - name: Debug Uploaded Artifact
        run: |
            echo "Uploaded artifact size: $(du -sh ${{ steps.upload_artifact.outputs.artifact_path }})"
