#  Description: This workflow is tigger on close event   to check for stale pull requests and close them after two days of inactivity.
name: Create Tag on Merge to master

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  create-tag:
    runs-on: ubuntu-latest

    env:
      CREATE_TAG: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.base.ref == 'master' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Read version from file
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      
      - name: Create tag
        run: |
          git tag -a $VERSION -m "Version $VERSION"
          echo "Created tag: $VERSION"
        if: ${{ env.CREATE_TAG }}
      
      - name: Push tag
        run: git push origin $VERSION
        if: ${{ env.CREATE_TAG }}