#  Description: This workflow is tigger on close event   to check for stale pull requests and close them after two days of inactivity.
name: Create Tag on Merge to master

on:
  pull_request:
    types: [closed]
    branches:
      - master


jobs:
  create-tag:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Read version from file
        id: version
        run: echo ::set-output name=VERSION::$(cat VERSION)
      
      - name: Create tag
        run: git tag -a ${{ steps.version.outputs.VERSION }} -m "Version ${{ steps.version.outputs.VERSION }}"
        if: github.event_name == 'issues' && github.event.action == 'closed' && github.ref == 'refs/heads/master'
      
      - name: Push tag
        run: git push origin ${{ steps.version.outputs.VERSION }}
        if: github.event_name == 'issues' && github.event.action == 'closed' && github.ref == 'refs/heads/master'